from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (
        QApplication, QWidget,
        QHBoxLayout, QVBoxLayout,
        QGroupBox, QButtonGroup, QRadioButton,  
        QPushButton, QLabel)
from random import randint, shuffle


'''СОЗДАНИЕ КЛАССА, КОТОРЫЙ БУДЕТ СОХРАНЯТЬ ВОПРОСЫ И ОТВЕТЫ'''

class Question():
    ''' содержит вопрос, правильный ответ и три неправильных'''
    def __init__(self, question, right_answer, wrong1, wrong2, wrong3):
        # все строки надо задать при создании объекта, они запоминаются в свойства
        self.question = question
        self.right_answer = right_answer
        self.wrong1 = wrong1
        self.wrong2 = wrong2
        self.wrong3 = wrong3

'ДОБАВЛЕНИЕ ВАРИАНТОВ ОТВЕТА'
questions_list = [] #создание спика для хранения вопросов
questions_list.append(Question('В каком году вышла игра (God of war Ragnarok)', '2022', '2018', '2010', '2005'))
questions_list.append(Question('Какого нет цвета на флаге России?', 'Зелёный', 'Красный', 'Белый', 'Синий'))
questions_list.append(Question('Национальная хижина якутов', 'Ураса', 'Юрта', 'Иглу', 'Хата'))
questions_list.append(Question('Какого нет цвета на флаге России?', 'Зелёный', 'Красный', 'Белый', 'Синий'))
questions_list.append(Question('Чего нет в шаурме?', 'Огурца', 'Мяса', 'Манго', 'Соус'))
questions_list.append(Question('Где был настоящий тюр в God of war Ragnarok?', 'Нифльхейм', 'Мидгард', 'Асгард', 'Йотунхейм'))
questions_list.append(Question('Почему Кратос белый?', 'Потомучто на нем прах жены и дочери', 'Потомучто не чёрный', 'Потомучто он родился таким ', 'Потомучто служил у Ареса'))
questions_list.append(Question('Как звучит теорема Пифагора?','Квадрат гипотенузы равен сумме квадратов катета','Не знаю не учил','Высоту умножить на ширину и узнается площадь трапеции',' нахождение площади треугольника это- половину высоты умножить на основание'))
questions_list.append(Question('какая формула теоремы пифагора?','c²= a²+b²','c²=a+b','x²+7x²-21=0','ax=-x²'))
questions_list.append(Question('СКОЛЬКО СПЯТ ГОРИЛЛЫ?','14 часов','7 часов','6 часов','Вообще не спят' ))
questions_list.append(Question('Сколько материков на Земле?','6','8','5','4' ))
questions_list.append(Question('Сколько океанов на Земле?','4','6','7','5'))
questions_list.append(Question('Как по английскии будет Ковёр?','carpet','table','bathroom','world' ))
questions_list.append(Question('Сколько стоит жвачка за 2 рубля?','2 рубля',' 4 рубля','1 рубль','6 рублей'))
questions_list.append(Question('СКОЛЬКО СПЯТ ГОРИЛЛЫ?','14 часов','7 часов','6 часов','Вообще не спят' ))
questions_list.append(Question('Какую вершину сложно покорить?','Вершину Эвереста','Вершина того самого небоскреба в дубаях','Вершина Треугольника с тупыми углами','ДА' ))
questions_list.append(Question('Кто такой ЧИНГИСХАН?','Первый хан Монгольской империи','Кто то там','да','нет'))




'''СОЗДАНИЕ ОСНОВНЫХ ВИДЖЕТОВ'''
 
app = QApplication([]) #приложение
btn_OK = QPushButton('Ответить') #кнопка
lb_Question = QLabel('Самый сложный вопрос в мире!') #текст вопроса
 
'''СОЗДАНИЕ И НАСТРОЙКА ГРУППЫ ВОПРОСОВ'''
 
RadioGroupBox = QGroupBox("Варианты ответов") #создание группы для объединения виджетов
 
rbtn_1 = QRadioButton('Вариант 1') #создание кнопок-переключателей
rbtn_2 = QRadioButton('Вариант 2')
rbtn_3 = QRadioButton('Вариант 3')
rbtn_4 = QRadioButton('Вариант 4')
 
RadioGroup = QButtonGroup() #создание группы для объединения кнопок
RadioGroup.addButton(rbtn_1)
RadioGroup.addButton(rbtn_2)
RadioGroup.addButton(rbtn_3)
RadioGroup.addButton(rbtn_4)
 
layout_ans1 = QHBoxLayout() #создание направляющих линий
layout_ans2 = QVBoxLayout()
layout_ans3 = QVBoxLayout()
layout_ans2.addWidget(rbtn_1) #добавление кнопок к направляющим линиям
layout_ans2.addWidget(rbtn_2)
layout_ans3.addWidget(rbtn_3)
layout_ans3.addWidget(rbtn_4)
 
layout_ans1.addLayout(layout_ans2) #добавление вертикальных линий с кнопками к основной горизонтальной линни
layout_ans1.addLayout(layout_ans3)
 
RadioGroupBox.setLayout(layout_ans1) #добавление горизонтальной линии со всеми кнопками в группу-виджет
 
'''СОЗДАНИЕ И НАСТРОЙКА ГРУППЫ ОТВЕТОВ'''  
 
AnsGroupBox = QGroupBox("Результат теста")  #создание группы для объединения виджетов
lb_Result = QLabel('прав ты или нет?')  #виджеты с надписями
lb_Correct = QLabel('ответ будет тут!')
layout_res = QVBoxLayout() #создание вертикальной линии
layout_res.addWidget(lb_Result, alignment=(Qt.AlignLeft | Qt.AlignTop)) #добавление нужных виджетов и настройка расположения
layout_res.addWidget(lb_Correct, alignment=Qt.AlignHCenter, stretch=2)
AnsGroupBox.setLayout(layout_res) #добавление вертикального линия в группу для виджетов
 
'''НАСТРОЙКА ВНЕШНЕГО ВИДА ОСНОВНОГО ОКНА'''
 
layout_line1 = QHBoxLayout() #направляющие линии
layout_line2 = QHBoxLayout()
layout_line3 = QHBoxLayout()
 
layout_line1.addWidget(lb_Question, alignment=(Qt.AlignHCenter | Qt.AlignVCenter)) #прикрепление виджетов к направлющим линиям
layout_line2.addWidget(RadioGroupBox)  
layout_line2.addWidget(AnsGroupBox)  
AnsGroupBox.hide() #скрытие группы ответов
 
layout_line3.addStretch(1) #настройка внешнего вида
layout_line3.addWidget(btn_OK, stretch=2) # кнопка должна быть большой
layout_line3.addStretch(1)
 
layout_card = QVBoxLayout() #создание главной направляющей
 
layout_card.addLayout(layout_line1, stretch=2) #прикрепление вторичных направляющих к главной и их настройка
layout_card.addLayout(layout_line2, stretch=8)
layout_card.addStretch(1)
layout_card.addLayout(layout_line3, stretch=1)
layout_card.addStretch(1)
layout_card.setSpacing(5) # пробелы между содержимым
 
'''ФУНКЦИИ ДЛЯ ОБРАБОТКИ ОТВЕТОВ'''
 
answers = [rbtn_1, rbtn_2, rbtn_3, rbtn_4] # установка кнопок-переключателей в список
 
def show_result(res):
    ''' показать результат - установим переданный текст в надпись "результат" и покажем нужную панель '''
    lb_Result.setText(res)
    ''' показать панель ответов '''
    RadioGroupBox.hide()
    AnsGroupBox.show()
    btn_OK.setText('Следующий вопрос')
 
 
def show_question():
    ''' показать панель вопросов '''
    RadioGroupBox.show()
    AnsGroupBox.hide()
    btn_OK.setText('Ответить')
    RadioGroup.setExclusive(False) # сняли ограничения, чтобы можно было сбросить выбор радиокнопки
    rbtn_1.setChecked(False)
    rbtn_2.setChecked(False)
    rbtn_3.setChecked(False)
    rbtn_4.setChecked(False)
    RadioGroup.setExclusive(True) # вернули ограничения, теперь только одна радиокнопка может быть выбрана
 
def check_answer():
    ''' если выбран какой-то вариант ответа, то надо проверить и показать панель ответов'''
    if answers[0].isChecked():
        show_result('Правильно!')
        window.score += 1
        print('Статистика\n-Всего вопросов: ', window.total, '\n-Правильных ответов: ', window.score)
        print('Рейтинг: ', (window.score/window.total*100), '%')
    else:
        if answers[1].isChecked() or answers[2].isChecked() or answers[3].isChecked():
            show_result('Неверно!')
            print('Рейтинг: ', (window.score/window.total*100), '%')




    ''' временная функция, которая позволяет нажатием на кнопку вызывать по очереди
    show_result() либо show_question() '''
def check_btn():
    if 'Ответить' == btn_OK.text():
        check_answer()
    else:
        next_question()


def next_question():
    ''' задает следующий вопрос из списка '''
    
    window.total += 1
    print('Статистика\n-Всего вопросов: ', window.total, '\n-Правильных ответов: ', window.score)
    cur_question = randint(0, len(questions_list) - 1)  # нам не нужно старое значение, 
                                                        # поэтому можно использовать локальную переменную! 
            # случайно взяли вопрос в пределах списка
            # если внести около сотни слов, то редко будет повторяться
    q = questions_list[cur_question] # взяли вопрос
    ask(q) # спросили
 
def ask(q: Question):
    ''' функция записывает значения вопроса и ответов в соответствующие виджеты,
    при этом варианты ответов распределяются случайным образом'''
    shuffle(answers)
    answers[0].setText(q.right_answer)
    answers[1].setText(q.wrong1)
    answers[2].setText(q.wrong2)
    answers[3].setText(q.wrong3)
    lb_Question.setText(q.question)
    lb_Correct.setText(q.right_answer)
    show_question()
 
 
'''СОЗДАНИЕ И НАСТРОЙКА ОКНА'''

window = QWidget()
window.score = 0
window.total = 0
window.setLayout(layout_card) #добавление в окно главного виджета
window.setWindowTitle('Memo Card')
window.resize(400, 300)

next_question()
btn_OK.clicked.connect(check_btn) # проверяем, что панель ответов показывается при нажатии на кнопку
 
window.show()
app.exec()
